# Мы переопределяем только эти значения!

# 1. Другой текст на входе (чтобы видеть разницу)
# Но у нас жестко зашит код Python, так что поменяем количество реплик
replicaCount: 1  # На тесте нам не нужно 3 штуки, экономим ресурсы

# 2. Другой адрес входа
ingress:
  enabled: true
  hosts:
    - host: "dev.100.126.89.59.nip.io" # Добавим префикс dev.
      paths:
        - path: /
          pathType: Prefix
